### ISSUE TITLE
Allow a helpdesk to be put "On Hold"

### ISSUE THREAD

**Issue by CLCmatmcmahon** [atomicjam/helpdesk#125]
This could happen for a number of reasons and may be sensible to tie into the scheduling system - i.e.  put on hold until Easter then the helpdesk automatically comes back to normal helpdesk.

**Comment by atomicjam** [comment]
calls can now be marked as on hold, for things like awaiting external parts etc. calls still remain in engineers list at this point, as part of the scheduling system I will add the ability to turn Helpdesk ticket into a scheduled event in the future, only managers will have access, so a managers can defer a helpdesk ticket to a future time to stop engineers deferring tickets to avoid work.
