### ISSUE TITLE
Reason for issue

### ISSUE THREAD

**Issue by atomicjam** [atomicjam/helpdesk#253]
One question, when updating a call and filling in the reason for issue box it would be nice to able to include more than one option from the drop down menu. Often we have the need to say rubbish left by contractors & unable to attend due to staffing problems. Could we have the ability to choose a maximum of say 2/3 menu items to better explain the issue?
 
Regards
Andy

**Comment by CLCmatmcmahon** [comment]
Got to be careful here.  May dilute the main reason.  What about a text box for other comments ?

**Comment by atomicjam** [comment]
moving issues to clc fork
